version: 2.1

jobs:
  build-and-test:
    docker:
    - image: circleci/node:14

    steps:
    - checkout
    - run: npm install
    - run: npm run build
    - run: npm run test

  deploy:
    docker:
    - image: circleci/node:14

    steps:
    - checkout
    - run: npm install
    - run: npm run build
    - run: npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build-and-test
    - deploy:
        requires:
        - build-and-test
        filters:
          branches:
            only: main